export type QuizQuestion = {
  soalan: string;
  pilihan: string[];
  jawapan: number; // index 0-based
  nota?: string;
};

const SAINS_D2: QuizQuestion[] = [
  { soalan: "Apakah proses tumbuhan membuat makanan?", pilihan: ["Respirasi", "Fotosintesis", "Evaporasi", "Kondensasi"], jawapan: 1 },
  { soalan: "Apakah gas yang dihasilkan semasa fotosintesis?", pilihan: ["Karbon dioksida", "Nitrogen", "Oksigen", "Hidrogen"], jawapan: 2 },
  { soalan: "Apakah gas yang diserap tumbuhan semasa fotosintesis?", pilihan: ["Oksigen", "Nitrogen", "Karbon dioksida", "Hidrogen"], jawapan: 2 },
  { soalan: "Tiga keadaan jirim ialah?", pilihan: ["pepejal cecair wap", "pepejal cecair gas", "pepejal gas wap", "cecair gas wap"], jawapan: 1 },
  { soalan: "Contoh pepejal ialah?", pilihan: ["air", "udara", "batu", "wap"], jawapan: 2 },
  { soalan: "Contoh cecair ialah?", pilihan: ["batu", "kayu", "air", "besi"], jawapan: 2 },
  { soalan: "Contoh gas ialah?", pilihan: ["batu", "kayu", "air", "udara"], jawapan: 3 },
  { soalan: "Apakah yang berlaku kepada pepejal apabila dipanaskan?", pilihan: ["membeku", "melebur", "menyejat", "memampat"], jawapan: 1 },
  { soalan: "Apakah yang berlaku kepada cecair apabila dipanaskan?", pilihan: ["membeku", "melebur", "menyejat", "memampat"], jawapan: 2 },
  { soalan: "Kitaran air bermula dengan?", pilihan: ["hujan", "awan", "penyejatan", "kondensasi"], jawapan: 2 },
  { soalan: "Haiwan yang bertelur dipanggil?", pilihan: ["mamalia", "reptilia", "ovipar", "vivipar"], jawapan: 2 },
  { soalan: "Haiwan yang melahirkan anak dipanggil?", pilihan: ["mamalia", "reptilia", "ovipar", "vivipar"], jawapan: 3 },
  { soalan: "Magnet menarik benda yang diperbuat daripada?", pilihan: ["kayu", "plastik", "besi", "kaca"], jawapan: 2 },
  { soalan: "Cahaya bergerak dalam garis?", pilihan: ["bengkok", "lurus", "melengkung", "zigzag"], jawapan: 1 },
  { soalan: "Kita tidak boleh mendengar bunyi di?", pilihan: ["dalam air", "dalam tanah", "angkasa lepas", "dalam bilik"], jawapan: 2 },
];

const BAHASA_MELAYU_D3: QuizQuestion[] = [
  { soalan: "Apakah maksud peribahasa 'bagai menatang minyak yang penuh'?", pilihan: ["Menjaga dengan teliti", "Membuang masa", "Berlaku cuai", "Tidak peduli"], jawapan: 0 },
  { soalan: "Pilih ayat pasif yang betul:", pilihan: ["Ali membaca buku", "Buku dibaca oleh Ali", "Buku membaca Ali", "Ali buku membaca"], jawapan: 1 },
  { soalan: "Apakah imbuhan dalam perkataan 'pelajaran'?", pilihan: ["pe...an", "pe", "an", "jar"], jawapan: 0 },
  { soalan: "Pilih kata adjektif:", pilihan: ["berlari", "dengan", "indah", "meja"], jawapan: 2 },
  { soalan: "Apakah kata ganti nama diri ketiga?", pilihan: ["saya", "kamu", "dia", "kami"], jawapan: 2 },
  { soalan: "Pilih ayat yang menggunakan kata hubung dengan betul:", pilihan: ["Ali dan Abu pergi ke sekolah", "Ali pergi dan sekolah", "Ali Abu dan pergi", "Pergi Ali dan Abu"], jawapan: 0 },
  { soalan: "Apakah maksud peribahasa 'bersatu teguh bercerai roboh'?", pilihan: ["Perpecahan itu kuat", "Perpaduan itu kuat", "Bergaduh itu baik", "Bersatu itu susah"], jawapan: 1 },
  { soalan: "Pilih perkataan majmuk yang betul:", pilihan: ["jalanraya", "jalan raya", "jalan-raya", "jalan_raya"], jawapan: 1 },
  { soalan: "Apakah kata ulang bagi 'budak'?", pilihan: ["budak budak", "budak-budak", "budakbudak", "budaks"], jawapan: 1 },
  { soalan: "Pilih kata kerja transitif:", pilihan: ["tidur", "berlari", "memukul", "duduk"], jawapan: 2 },
  { soalan: "Apakah imbuhan dalam perkataan 'kebersihan'?", pilihan: ["ke...an", "ke", "an", "bersih"], jawapan: 0 },
  { soalan: "Pilih ayat tanya yang betul:", pilihan: ["Ke mana kamu pergi", "Ke mana kamu pergi?", "ke mana kamu pergi?", "Ke mana Kamu pergi?"], jawapan: 1 },
  { soalan: "Apakah maksud kata 'dedikasi'?", pilihan: ["Malas", "Bersungguh-sungguh", "Cuai", "Tidak serius"], jawapan: 1 },
  { soalan: "Pilih kata nama abstrak:", pilihan: ["meja", "kucing", "kasih sayang", "buku"], jawapan: 2 },
  { soalan: "Apakah sinonim 'indah'?", pilihan: ["hodoh", "buruk", "cantik", "kotor"], jawapan: 2 },
];

const MATE_D3: QuizQuestion[] = [
  { soalan: "234 + 567 = ?", pilihan: ["791", "801", "811", "821"], jawapan: 1 },
  { soalan: "856 - 378 = ?", pilihan: ["468", "478", "488", "498"], jawapan: 1 },
  { soalan: "7 × 8 = ?", pilihan: ["54", "56", "58", "60"], jawapan: 1 },
  { soalan: "9 × 6 = ?", pilihan: ["48", "54", "56", "60"], jawapan: 1 },
  { soalan: "72 ÷ 8 = ?", pilihan: ["7", "8", "9", "10"], jawapan: 2 },
  { soalan: "63 ÷ 7 = ?", pilihan: ["7", "8", "9", "10"], jawapan: 2 },
  { soalan: "Nilai digit 4 dalam 3456?", pilihan: ["4", "40", "400", "4000"], jawapan: 2 },
  { soalan: "Bundarkan 456 ke ratus terdekat?", pilihan: ["400", "450", "500", "460"], jawapan: 2 },
  { soalan: "1/2 + 1/4 = ?", pilihan: ["1/6", "2/6", "3/4", "2/4"], jawapan: 2 },
  { soalan: "3/4 - 1/4 = ?", pilihan: ["1/4", "2/4", "3/8", "4/8"], jawapan: 1 },
  { soalan: "0.5 + 0.3 = ?", pilihan: ["0.7", "0.8", "0.9", "1.0"], jawapan: 1 },
  { soalan: "2345 + 1234 = ?", pilihan: ["3479", "3579", "3679", "3779"], jawapan: 1 },
  { soalan: "5000 - 2345 = ?", pilihan: ["2555", "2655", "2755", "2855"], jawapan: 1 },
  { soalan: "Luas segiempat 6cm × 4cm = ?", pilihan: ["20cm²", "24cm²", "28cm²", "32cm²"], jawapan: 1 },
  { soalan: "Perimeter segitiga 3cm, 4cm, 5cm = ?", pilihan: ["10cm", "12cm", "14cm", "16cm"], jawapan: 1 },
];

const BI_D3: QuizQuestion[] = [
  { soalan: "Choose the correct sentence:", pilihan: ["She go to market", "She goes to market", "She going to market", "She gone to market"], jawapan: 1 },
  { soalan: "Past tense of 'write'?", pilihan: ["writed", "writes", "written", "wrote"], jawapan: 3 },
  { soalan: "Plural of 'leaf'?", pilihan: ["leafs", "leafes", "leaves", "leafies"], jawapan: 2 },
  { soalan: "Choose the adjective:", pilihan: ["run", "book", "beautiful", "and"], jawapan: 2 },
  { soalan: "Choose the adverb:", pilihan: ["beautiful", "quickly", "swim", "table"], jawapan: 1 },
  { soalan: "I ___ reading a book now.", pilihan: ["am", "is", "are", "be"], jawapan: 0 },
  { soalan: "She ___ to school yesterday.", pilihan: ["go", "goes", "went", "going"], jawapan: 2 },
  { soalan: "They ___ playing football tomorrow.", pilihan: ["was", "were", "will be", "are"], jawapan: 2 },
  { soalan: "Choose correct use of article:", pilihan: ["I saw a elephant", "I saw an elephant", "I saw the elephant yesterday", "Both B and C"], jawapan: 3 },
  { soalan: "Synonym of 'happy'?", pilihan: ["sad", "angry", "joyful", "tired"], jawapan: 2 },
  { soalan: "Antonym of 'brave'?", pilihan: ["bold", "fearless", "cowardly", "strong"], jawapan: 2 },
  { soalan: "What is a simile?", pilihan: ["comparing using like or as", "action word", "naming word", "describing word"], jawapan: 0 },
  { soalan: "Example of simile?", pilihan: ["The cat runs", "She is as fast as a cheetah", "He runs quickly", "The flower is beautiful"], jawapan: 1 },
  { soalan: "Choose conjunction:", pilihan: ["beautiful", "run", "but", "quickly"], jawapan: 2 },
  { soalan: "Choose preposition:", pilihan: ["run", "beautiful", "and", "under"], jawapan: 3 },
];

const JAWI_D3: QuizQuestion[] = [
  { soalan: "Ejaan Jawi bagi 'perpustakaan'?", pilihan: ["ڤرڤوستاکان", "ڤرڤستاکان", "ڤرڤوسطاکان", "ڤرڤستکان"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi 'kemerdekaan'?", pilihan: ["کمرديکان", "کمردیکاءن", "کمرديکاءن", "کيمرديکان"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'pembelajaran'?", pilihan: ["ڤمبلاجرن", "ڤمبلاجاران", "ڤيمبلاجاران", "ڤمبلجران"], jawapan: 1 },
  { soalan: "Ejaan Jawi bagi 'kecemerlangan'?", pilihan: ["کچمرلڠن", "کيچمرلاڠن", "کچمرلاڠن", "کيچمرلڠن"], jawapan: 2 },
  { soalan: "Huruf Jawi ڬ berbunyi?", pilihan: ["ka", "ga", "ha", "na"], jawapan: 1 },
  { soalan: "Huruf Jawi ۏ berbunyi?", pilihan: ["wa", "va", "fa", "ba"], jawapan: 1 },
  { soalan: "Jawi مدرسة bermaksud?", pilihan: ["rumah", "masjid", "sekolah", "kedai"], jawapan: 2 },
  { soalan: "Jawi معلم bermaksud?", pilihan: ["pelajar", "guru", "doktor", "polis"], jawapan: 1 },
  { soalan: "Jawi كتاب bermaksud?", pilihan: ["pen", "meja", "buku", "kerusi"], jawapan: 2 },
  { soalan: "Jawi مدينة bermaksud?", pilihan: ["kampung", "bandar", "negara", "dunia"], jawapan: 1 },
  { soalan: "Berapa huruf Jawi asas?", pilihan: ["26", "28", "30", "32"], jawapan: 2 },
  { soalan: "Berapa huruf tambahan Jawi Melayu?", pilihan: ["4", "5", "6", "7"], jawapan: 2 },
  { soalan: "Jawi نيڬارا bermaksud?", pilihan: ["bandar", "kampung", "negara", "dunia"], jawapan: 2 },
  { soalan: "Jawi بهاسا bermaksud?", pilihan: ["tulisan", "bahasa", "budaya", "bangsa"], jawapan: 1 },
  { soalan: "Jawi مردياک bermaksud?", pilihan: ["merdeka", "berduka", "bersuka", "berdekat"], jawapan: 0 },
];

const PI_D3: QuizQuestion[] = [
  { soalan: "Berapa jumlah nabi dan rasul wajib diketahui?", pilihan: ["20", "25", "30", "35"], jawapan: 1 },
  { soalan: "Nabi yang diutus kepada kaum Ad?", pilihan: ["Nabi Nuh", "Nabi Hud", "Nabi Soleh", "Nabi Lut"], jawapan: 1 },
  { soalan: "Nabi yang diutus kepada kaum Thamud?", pilihan: ["Nabi Nuh", "Nabi Hud", "Nabi Soleh", "Nabi Lut"], jawapan: 2 },
  { soalan: "Kitab Zabur diturunkan kepada?", pilihan: ["Nabi Musa", "Nabi Isa", "Nabi Daud", "Nabi Muhammad"], jawapan: 2 },
  { soalan: "Malaikat Jibril bertugas?", pilihan: ["menurunkan hujan", "menyampaikan wahyu", "mencabut nyawa", "meniup sangkakala"], jawapan: 1 },
  { soalan: "Sifat wajib Allah 'Wujud' bermaksud?", pilihan: ["Kekal", "Ada", "Maha Esa", "Sedia Ada"], jawapan: 1 },
  { soalan: "Surah Al-Fatihah ada berapa ayat?", pilihan: ["5", "6", "7", "8"], jawapan: 2 },
  { soalan: "Hukum solat 5 waktu?", pilihan: ["sunat", "harus", "wajib", "makruh"], jawapan: 2 },
  { soalan: "Solat Jumaat wajib bagi?", pilihan: ["semua orang", "lelaki Islam baligh", "perempuan Islam", "kanak-kanak"], jawapan: 1 },
  { soalan: "Bulan puasa ialah?", pilihan: ["Syawal", "Zulhijjah", "Ramadan", "Muharram"], jawapan: 2 },
  { soalan: "Zakat fitrah dibayar pada bulan?", pilihan: ["Syawal", "Ramadan", "Zulhijjah", "Muharram"], jawapan: 1 },
  { soalan: "Sifat mahmudah contohnya?", pilihan: ["dengki", "sombong", "jujur", "bakhil"], jawapan: 2 },
  { soalan: "Sifat mazmumah contohnya?", pilihan: ["jujur", "amanah", "sabar", "dengki"], jawapan: 3 },
  { soalan: "Islam bermaksud?", pilihan: ["tunduk patuh kepada Allah", "bebas", "berani", "kuat"], jawapan: 0 },
  { soalan: "Kaabah terletak di?", pilihan: ["Madinah", "Palestin", "Makkah", "Taif"], jawapan: 2 },
];

const SAINS_D3: QuizQuestion[] = [
  { soalan: "Proses tumbuhan buat makanan?", pilihan: ["Respirasi", "Fotosintesis", "Evaporasi", "Kondensasi"], jawapan: 1 },
  { soalan: "Tiga keadaan jirim?", pilihan: ["pepejal cecair wap", "pepejal cecair gas", "pepejal gas wap", "cecair gas wap"], jawapan: 1 },
  { soalan: "Haiwan bertelur dipanggil?", pilihan: ["mamalia", "reptilia", "ovipar", "vivipar"], jawapan: 2 },
  { soalan: "Haiwan melahirkan anak dipanggil?", pilihan: ["mamalia", "reptilia", "ovipar", "vivipar"], jawapan: 3 },
  { soalan: "Magnet menarik benda dari?", pilihan: ["kayu", "plastik", "besi", "kaca"], jawapan: 2 },
  { soalan: "Cahaya bergerak dalam garis?", pilihan: ["bengkok", "lurus", "melengkung", "zigzag"], jawapan: 1 },
  { soalan: "Bumi mengelilingi matahari dalam?", pilihan: ["sehari", "sebulan", "setahun", "seminggu"], jawapan: 2 },
  { soalan: "Berapa planet dalam sistem suria?", pilihan: ["7", "8", "9", "10"], jawapan: 1 },
  { soalan: "Gas yang diserap tumbuhan semasa fotosintesis?", pilihan: ["Oksigen", "Nitrogen", "Karbon dioksida", "Hidrogen"], jawapan: 2 },
  { soalan: "Rantaian makanan bermula dengan?", pilihan: ["haiwan", "tumbuhan", "manusia", "bakteria"], jawapan: 1 },
  { soalan: "Haiwan herbivor makan?", pilihan: ["daging", "tumbuhan", "daging dan tumbuhan", "ikan"], jawapan: 1 },
  { soalan: "Haiwan karnivor makan?", pilihan: ["tumbuhan", "daging", "buah", "bijirin"], jawapan: 1 },
  { soalan: "Gerhana matahari berlaku apabila?", pilihan: ["bumi masuk bayang bulan", "bulan masuk bayang bumi", "matahari hilang", "bumi berhenti berputar"], jawapan: 0 },
  { soalan: "Graviti menarik benda ke arah?", pilihan: ["atas", "tepi", "bawah", "depan"], jawapan: 2 },
  { soalan: "Pemanasan global disebabkan oleh?", pilihan: ["lebih banyak pokok", "lebih banyak hujan", "peningkatan gas rumah hijau", "lebih banyak angin"], jawapan: 2 },
];

const BM_D4: QuizQuestion[] = [
  { soalan: "Apakah ayat majmuk?", pilihan: ["Ayat tunggal", "Gabungan dua ayat atau lebih", "Ayat pendek", "Ayat panjang"], jawapan: 1 },
  { soalan: "Pilih ayat majmuk:", pilihan: ["Ali pergi ke sekolah", "Ali pergi ke sekolah dan Abu duduk di rumah", "Ali dan Abu", "Pergi ke sekolah"], jawapan: 1 },
  { soalan: "Apakah kata sendi nama?", pilihan: ["dan", "tetapi", "di", "cantik"], jawapan: 2 },
  { soalan: "Apakah imbuhan apitan ke...an dalam?", pilihan: ["kebaikan", "berlari", "memukul", "jalan raya"], jawapan: 0 },
  { soalan: "Pilih kata tanya:", pilihan: ["dan", "tetapi", "di", "siapa"], jawapan: 3 },
  { soalan: "Apakah maksud peribahasa 'seperti air di daun keladi'?", pilihan: ["Tidak bertanggungjawab", "Tidak kekal", "Sangat setia", "Sangat rajin"], jawapan: 1 },
  { soalan: "Pilih kata penguat:", pilihan: ["sangat", "dan", "di", "berlari"], jawapan: 0 },
  { soalan: "Apakah pantun?", pilihan: ["Puisi bebas", "Puisi tradisional 4 baris", "Cerita panjang", "Dialog"], jawapan: 1 },
  { soalan: "Bahagian pantun yang mengandungi maksud?", pilihan: ["Pembayang", "Maksud", "Rima", "Irama"], jawapan: 1 },
  { soalan: "Pilih kata nafi:", pilihan: ["sangat", "tidak", "di", "dan"], jawapan: 1 },
  { soalan: "Apakah dialog?", pilihan: ["Cerita pendek", "Perbualan antara dua orang atau lebih", "Puisi", "Pantun"], jawapan: 1 },
  { soalan: "Imbuhan men dalam 'menyanyi'?", pilihan: ["me", "men", "meny", "nyanyi"], jawapan: 2 },
  { soalan: "Pilih kata bilangan:", pilihan: ["cantik", "berlari", "tiga orang", "di"], jawapan: 2 },
  { soalan: "Apakah maksud 'dedikasi'?", pilihan: ["Malas", "Bersungguh-sungguh", "Cuai", "Tidak serius"], jawapan: 1 },
  { soalan: "Pilih kata majmuk:", pilihan: ["budak-budak", "jalan raya", "cantik", "berlari"], jawapan: 1 },
];

const MATE_D4: QuizQuestion[] = [
  { soalan: "2345 + 3456 = ?", pilihan: ["5791", "5801", "5811", "5821"], jawapan: 1 },
  { soalan: "8765 - 4321 = ?", pilihan: ["4334", "4344", "4444", "4454"], jawapan: 2 },
  { soalan: "12 × 8 = ?", pilihan: ["86", "96", "106", "116"], jawapan: 1 },
  { soalan: "144 ÷ 12 = ?", pilihan: ["10", "11", "12", "13"], jawapan: 2 },
  { soalan: "2/3 + 1/3 = ?", pilihan: ["3/3", "1", "3/6", "A dan B"], jawapan: 3 },
  { soalan: "3/4 - 1/2 = ?", pilihan: ["1/4", "2/4", "1/2", "2/2"], jawapan: 0 },
  { soalan: "0.75 + 0.25 = ?", pilihan: ["0.9", "1.0", "1.1", "1.2"], jawapan: 1 },
  { soalan: "Luas segiempat 12cm × 8cm = ?", pilihan: ["80cm²", "86cm²", "96cm²", "106cm²"], jawapan: 2 },
  { soalan: "Perimeter segiempat 12cm × 8cm = ?", pilihan: ["36cm", "40cm", "44cm", "48cm"], jawapan: 1 },
  { soalan: "Sudut tegak berapa darjah?", pilihan: ["45", "90", "180", "360"], jawapan: 1 },
  { soalan: "Sudut tirus kurang daripada?", pilihan: ["45 darjah", "90 darjah", "180 darjah", "360 darjah"], jawapan: 1 },
  { soalan: "12345 + 23456 = ?", pilihan: ["35791", "35801", "35811", "35821"], jawapan: 1 },
  { soalan: "50000 - 23456 = ?", pilihan: ["26444", "26544", "26644", "26744"], jawapan: 1 },
  { soalan: "25 × 4 = ?", pilihan: ["90", "95", "100", "105"], jawapan: 2 },
  { soalan: "200 ÷ 8 = ?", pilihan: ["23", "24", "25", "26"], jawapan: 2 },
];

const BI_D4: QuizQuestion[] = [
  { soalan: "What is a compound sentence?", pilihan: ["One main clause", "Two or more main clauses joined", "A short sentence", "A long sentence"], jawapan: 1 },
  { soalan: "Choose compound sentence:", pilihan: ["She runs fast", "She runs fast and he walks slowly", "Running fast", "Fast runner"], jawapan: 1 },
  { soalan: "What is present continuous tense?", pilihan: ["I eat", "I ate", "I am eating", "I will eat"], jawapan: 2 },
  { soalan: "She ___ singing now.", pilihan: ["am", "is", "are", "be"], jawapan: 1 },
  { soalan: "They ___ playing football now.", pilihan: ["am", "is", "are", "be"], jawapan: 2 },
  { soalan: "What is a pronoun?", pilihan: ["naming word", "word that replaces noun", "action word", "describing word"], jawapan: 1 },
  { soalan: "Choose pronoun:", pilihan: ["book", "run", "she", "quickly"], jawapan: 2 },
  { soalan: "Synonym of 'angry'?", pilihan: ["happy", "furious", "sad", "tired"], jawapan: 1 },
  { soalan: "Antonym of 'ancient'?", pilihan: ["old", "modern", "antique", "historical"], jawapan: 1 },
  { soalan: "What is alliteration?", pilihan: ["rhyming words", "repetition of same sound at start of words", "simile", "metaphor"], jawapan: 1 },
  { soalan: "Example of alliteration?", pilihan: ["She is like a rose", "Peter Piper picked peppers", "The moon is a coin", "He runs quickly"], jawapan: 1 },
  { soalan: "Choose correct sentence:", pilihan: ["He dont go", "He doesnt go", "He does not go", "both B and C"], jawapan: 3 },
  { soalan: "Past continuous: She ___ when I called.", pilihan: ["sleep", "sleeps", "was sleeping", "slept"], jawapan: 2 },
  { soalan: "Choose possessive pronoun:", pilihan: ["she", "her", "hers", "herself"], jawapan: 2 },
  { soalan: "What is onomatopoeia?", pilihan: ["comparing using like", "word that sounds like its meaning", "direct comparison", "same sound repetition"], jawapan: 1 },
];

const JAWI_D4: QuizQuestion[] = [
  { soalan: "Ejaan Jawi bagi 'kecemerlangan'?", pilihan: ["کچمرلڠن", "کيچمرلاڠن", "کچمرلاڠن", "کيچمرلڠن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'persekitaran'?", pilihan: ["ڤرسيکيتارن", "ڤيرسيکيتارن", "ڤرسکيتارن", "ڤيرسکيتارن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi 'pembangunan'?", pilihan: ["ڤمباڠونن", "ڤيمباڠونن", "ڤمبانڬونن", "ڤيمبانڬونن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'keselamatan'?", pilihan: ["کسلامتن", "کيسلامتن", "کسيلامتن", "کيسيلامتن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'tanggungjawab'?", pilihan: ["تاڠڬوڠجاوب", "تڠڬوڠجاوب", "تاڠڬوڠجوب", "تڠڬوڠجوب"], jawapan: 0 },
  { soalan: "Jawi ڤمبانڬونن bermaksud?", pilihan: ["persekitaran", "pembangunan", "keselamatan", "tanggungjawab"], jawapan: 1 },
  { soalan: "Jawi کسيلامتن bermaksud?", pilihan: ["persekitaran", "pembangunan", "keselamatan", "tanggungjawab"], jawapan: 2 },
  { soalan: "Jawi تاڠڬوڠجاوب bermaksud?", pilihan: ["persekitaran", "pembangunan", "keselamatan", "tanggungjawab"], jawapan: 3 },
  { soalan: "Berapa huruf Jawi asas?", pilihan: ["26", "28", "30", "32"], jawapan: 2 },
  { soalan: "Berapa huruf tambahan Jawi Melayu?", pilihan: ["4", "5", "6", "7"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'perkhidmatan'?", pilihan: ["ڤرخدمتن", "ڤيرخدمتن", "ڤرخيدمتن", "ڤيرخيدمتن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'kebebasan'?", pilihan: ["کببسن", "کيببسن", "کببيسن", "کيببيسن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'pengetahuan'?", pilihan: ["ڤڠتاهوان", "ڤيڠتاهوان", "ڤڠيتاهوان", "ڤيڠيتاهوان"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi 'kepimpinan'?", pilihan: ["کڤيمڤينن", "کيڤيمڤينن", "کڤمڤينن", "کيڤمڤينن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi 'kemasyarakatan'?", pilihan: ["کماسياراکتن", "کيماسياراکتن", "کماسارکتن", "کيماسارکتن"], jawapan: 0 },
];

const PI_D4: QuizQuestion[] = [
  { soalan: "Apakah maksud akhlak?", pilihan: ["Ilmu", "Budi pekerti", "Ibadat", "Aqidah"], jawapan: 1 },
  { soalan: "Akhlak mulia contohnya?", pilihan: ["dengki", "sombong", "tolong-menolong", "bakhil"], jawapan: 2 },
  { soalan: "Apakah maksud ukhuwah?", pilihan: ["persaingan", "persaudaraan", "permusuhan", "perdebatan"], jawapan: 1 },
  { soalan: "Solat berjemaah lebih afdal berapa kali ganda?", pilihan: ["17", "27", "37", "47"], jawapan: 1 },
  { soalan: "Apakah maksud amanah?", pilihan: ["berbohong", "boleh dipercayai", "sombong", "dengki"], jawapan: 1 },
  { soalan: "Apakah maksud istiqamah?", pilihan: ["berubah-ubah", "tidak konsisten", "tetap pendirian", "tidak sabar"], jawapan: 2 },
  { soalan: "Sirah Nabi bermaksud?", pilihan: ["hadis Nabi", "riwayat hidup Nabi", "doa Nabi", "sifat Nabi"], jawapan: 1 },
  { soalan: "Nabi Muhammad SAW lahir pada tahun?", pilihan: ["570M", "580M", "590M", "600M"], jawapan: 0 },
  { soalan: "Nabi Muhammad SAW mula menerima wahyu pada usia?", pilihan: ["30", "35", "40", "45"], jawapan: 2 },
  { soalan: "Peristiwa hijrah bermaksud?", pilihan: ["perang", "perpindahan dari Makkah ke Madinah", "kematian", "kelahiran"], jawapan: 1 },
  { soalan: "Tahun hijrah bermula pada?", pilihan: ["610M", "620M", "622M", "630M"], jawapan: 2 },
  { soalan: "Sahabat yang menemani Nabi hijrah?", pilihan: ["Umar", "Uthman", "Ali", "Abu Bakar"], jawapan: 3 },
  { soalan: "Apakah maksud tawaduk?", pilihan: ["sombong", "rendah diri", "pemarah", "dengki"], jawapan: 1 },
  { soalan: "Apakah maksud syukur?", pilihan: ["tidak bersyukur", "berterima kasih atas nikmat Allah", "sombong", "tamak"], jawapan: 1 },
  { soalan: "Apakah maksud sabar?", pilihan: ["mudah marah", "tidak mudah marah dan tabah", "suka mengalah", "tidak peduli"], jawapan: 1 },
];

const SAINS_D4: QuizQuestion[] = [
  { soalan: "Apakah sel?", pilihan: ["Unit terkecil makhluk hidup", "Organ", "Tisu", "Sistem"], jawapan: 0 },
  { soalan: "Sel tumbuhan berbeza dari sel haiwan kerana ada?", pilihan: ["nukleus", "dinding sel", "sitoplasma", "membran"], jawapan: 1 },
  { soalan: "Apakah fungsi kloroplas?", pilihan: ["menyimpan makanan", "kawalan sel", "fotosintesis", "pernafasan"], jawapan: 2 },
  { soalan: "Apakah ekosistem?", pilihan: ["sekumpulan haiwan", "sekumpulan tumbuhan", "komuniti organisma dan persekitaran", "rantaian makanan"], jawapan: 2 },
  { soalan: "Apakah habitat?", pilihan: ["makanan haiwan", "tempat tinggal organisma", "musuh semulajadi", "rantaian makanan"], jawapan: 1 },
  { soalan: "Apakah adaptasi?", pilihan: ["perpindahan", "penyesuaian diri dengan persekitaran", "pembiakan", "pemakanan"], jawapan: 1 },
  { soalan: "Tenaga boleh wujud dalam berapa bentuk?", pilihan: ["3", "4", "5", "banyak"], jawapan: 3 },
  { soalan: "Contoh tenaga kinetik?", pilihan: ["batu diam", "air mengalir", "spring termampat", "bateri"], jawapan: 1 },
  { soalan: "Contoh tenaga keupayaan?", pilihan: ["bola bergerak", "air mengalir", "batu di atas meja", "cahaya"], jawapan: 2 },
  { soalan: "Apakah tenaga boleh diperbaharui?", pilihan: ["minyak", "arang batu", "gas asli", "solar"], jawapan: 3 },
  { soalan: "Apakah tenaga tidak boleh diperbaharui?", pilihan: ["angin", "solar", "minyak", "air"], jawapan: 2 },
  { soalan: "Apakah pencemaran udara?", pilihan: ["air kotor", "udara tercemar", "tanah kotor", "bunyi bising"], jawapan: 1 },
  { soalan: "Apakah pencemaran air?", pilihan: ["udara tercemar", "air tercemar", "tanah kotor", "bunyi bising"], jawapan: 1 },
  { soalan: "Cara jimat tenaga elektrik?", pilihan: ["tinggalkan lampu hidup", "padam lampu bila keluar", "buka semua tingkap", "biarkan kipas hidup"], jawapan: 1 },
  { soalan: "Apakah kitar semula?", pilihan: ["buang sampah", "proses semula bahan", "bakar sampah", "tanam sampah"], jawapan: 1 },
];

const BM_D5: QuizQuestion[] = [
  { soalan: "Apakah novel?", pilihan: ["Puisi panjang", "Prosa panjang berbentuk cerpen", "Karya prosa panjang berbentuk naratif", "Dialog panjang"], jawapan: 2 },
  { soalan: "Apakah cerpen?", pilihan: ["Novel pendek", "Cerita pendek kurang 10000 patah perkataan", "Puisi", "Drama"], jawapan: 1 },
  { soalan: "Apakah tema dalam karya sastera?", pilihan: ["Watak", "Latar", "Persoalan utama yang disampaikan", "Plot"], jawapan: 2 },
  { soalan: "Apakah plot?", pilihan: ["Watak utama", "Susunan peristiwa dalam cerita", "Latar tempat", "Tema"], jawapan: 1 },
  { soalan: "Apakah watak protagonis?", pilihan: ["Watak jahat", "Watak utama yang baik", "Watak sampingan", "Watak neutral"], jawapan: 1 },
  { soalan: "Apakah watak antagonis?", pilihan: ["Watak baik", "Watak utama", "Watak yang menentang protagonis", "Watak sampingan"], jawapan: 2 },
  { soalan: "Apakah latar tempat?", pilihan: ["Masa cerita berlaku", "Tempat cerita berlaku", "Suasana cerita", "Watak cerita"], jawapan: 1 },
  { soalan: "Apakah latar masa?", pilihan: ["Tempat cerita berlaku", "Masa cerita berlaku", "Suasana cerita", "Watak cerita"], jawapan: 1 },
  { soalan: "Apakah sudut pandangan pertama?", pilihan: ["Pencerita luar", "Pencerita menggunakan aku atau saya", "Pencerita ketiga", "Pencerita kedua"], jawapan: 1 },
  { soalan: "Apakah gaya bahasa?", pilihan: ["Tema karya", "Cara pengarang menggunakan bahasa", "Plot cerita", "Watak cerita"], jawapan: 1 },
  { soalan: "Apakah imbuhan sisipan?", pilihan: ["Imbuhan di depan", "Imbuhan di belakang", "Imbuhan di tengah kata", "Imbuhan di depan dan belakang"], jawapan: 2 },
  { soalan: "Contoh imbuhan sisipan?", pilihan: ["berlari", "geletar", "kebaikan", "memukul"], jawapan: 1 },
  { soalan: "Apakah kata terbitan?", pilihan: ["Kata asal", "Kata yang menerima imbuhan", "Kata majmuk", "Kata ulang"], jawapan: 1 },
  { soalan: "Apakah maksud simpulan bahasa?", pilihan: ["Peribahasa panjang", "Ungkapan pendek dengan makna kiasan", "Pantun", "Sajak"], jawapan: 1 },
  { soalan: "Contoh simpulan bahasa?", pilihan: ["bersatu teguh bercerai roboh", "kaki bangku", "seperti air di daun keladi", "melentur buluh"], jawapan: 1 },
];

const MATE_D5: QuizQuestion[] = [
  { soalan: "23456 + 34567 = ?", pilihan: ["58023", "58013", "58033", "58043"], jawapan: 0 },
  { soalan: "75000 - 34567 = ?", pilihan: ["40333", "40433", "40533", "40633"], jawapan: 1 },
  { soalan: "15 × 15 = ?", pilihan: ["215", "225", "235", "245"], jawapan: 1 },
  { soalan: "360 ÷ 15 = ?", pilihan: ["22", "23", "24", "25"], jawapan: 2 },
  { soalan: "2/5 + 3/5 = ?", pilihan: ["5/5", "1", "5/10", "A dan B"], jawapan: 3 },
  { soalan: "3/4 - 1/8 = ?", pilihan: ["5/8", "6/8", "7/8", "2/4"], jawapan: 0 },
  { soalan: "1.25 + 2.75 = ?", pilihan: ["3.9", "4.0", "4.1", "4.2"], jawapan: 1 },
  { soalan: "Luas bulatan jejari 7cm = ?", pilihan: ["144cm²", "154cm²", "164cm²", "174cm²"], jawapan: 1 },
  { soalan: "Perimeter bulatan diameter 14cm = ?", pilihan: ["44cm", "54cm", "64cm", "74cm"], jawapan: 0 },
  { soalan: "Apakah nombor perdana?", pilihan: ["nombor boleh dibahagi banyak", "nombor hanya boleh dibahagi 1 dan dirinya", "nombor genap", "nombor ganjil"], jawapan: 1 },
  { soalan: "Nombor perdana antara 20 hingga 30?", pilihan: ["21,23", "23,29", "21,27", "23,27"], jawapan: 1 },
  { soalan: "345678 + 234567 = ?", pilihan: ["580245", "580145", "580345", "580045"], jawapan: 0 },
  { soalan: "500000 - 234567 = ?", pilihan: ["265333", "265433", "265533", "265633"], jawapan: 1 },
  { soalan: "25 × 25 = ?", pilihan: ["615", "625", "635", "645"], jawapan: 1 },
  { soalan: "1000 ÷ 25 = ?", pilihan: ["38", "39", "40", "41"], jawapan: 2 },
];

const BI_D5: QuizQuestion[] = [
  { soalan: "What is a complex sentence?", pilihan: ["one clause", "two independent clauses", "one main and one subordinate clause", "three clauses"], jawapan: 2 },
  { soalan: "Choose subordinating conjunction:", pilihan: ["and", "but", "or", "although"], jawapan: 3 },
  { soalan: "What is passive voice?", pilihan: ["subject does action", "subject receives action", "no subject", "no object"], jawapan: 1 },
  { soalan: "Example of passive voice:", pilihan: ["Ali reads book", "Book is read by Ali", "Ali is reading", "Reading book"], jawapan: 1 },
  { soalan: "Present perfect: She ___ finished.", pilihan: ["is", "was", "will", "has"], jawapan: 3 },
  { soalan: "What is reported speech?", pilihan: ["direct speech", "telling what someone said without quoting", "question", "command"], jawapan: 1 },
  { soalan: "Direct to reported: He said I am happy.", pilihan: ["He said he is happy", "He said he was happy", "He told happy", "He said am happy"], jawapan: 1 },
  { soalan: "What is conditional sentence?", pilihan: ["statement", "if-then sentence", "question", "command"], jawapan: 1 },
  { soalan: "First conditional: If it rains ___", pilihan: ["I stay home", "I stayed home", "I will stay home", "I would stay home"], jawapan: 2 },
  { soalan: "Second conditional: If I were rich ___", pilihan: ["I will buy car", "I would buy car", "I buy car", "I bought car"], jawapan: 1 },
  { soalan: "What is subject-verb agreement?", pilihan: ["subject and verb match in number", "subject and object match", "verb and object match", "no agreement needed"], jawapan: 0 },
  { soalan: "Choose correct: The children ___ playing.", pilihan: ["is", "was", "are", "has"], jawapan: 2 },
  { soalan: "What is direct speech?", pilihan: ["reported speech", "exact words in quotes", "indirect speech", "paraphrase"], jawapan: 1 },
  { soalan: "Choose correct reported speech: She said she likes music.", pilihan: ["She said I like music", "She said she liked music", "She told liked music", "She says she like music"], jawapan: 1 },
  { soalan: "What is an idiom?", pilihan: ["literal phrase", "phrase with figurative meaning", "simile", "metaphor"], jawapan: 1 },
];

const JAWI_D5: QuizQuestion[] = [
  { soalan: "Ejaan Jawi bagi kemasyarakatan?", pilihan: ["کماسياراکتن", "کيماسياراکتن", "کماسارکتن", "کيماسارکتن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi kepimpinan?", pilihan: ["کڤيمڤينن", "کيڤيمڤينن", "کڤمڤينن", "کيڤمڤينن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi pembangunan?", pilihan: ["ڤمباڠونن", "ڤيمباڠونن", "ڤمبانڬونن", "ڤيمبانڬونن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi keharmonian?", pilihan: ["کهارمونين", "کيهارمونين", "کهرمونين", "کيهرمونين"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi perjuangan?", pilihan: ["ڤرجواڠن", "ڤيرجواڠن", "ڤرجوڠن", "ڤيرجوڠن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi kejayaan?", pilihan: ["کجاياءن", "کيجاياءن", "کجايأن", "کيجايأن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi semangat?", pilihan: ["سماڠت", "سيماڠت", "سمڠت", "سيمڠت"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi keberanian?", pilihan: ["کبرانين", "کيبرانين", "کبراءنين", "کيبراءنين"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi ketabahan?", pilihan: ["کتابهن", "کيتابهن", "کتبهن", "کيتبهن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi kesabaran?", pilihan: ["کصبارن", "کيصبارن", "کسبارن", "کيسبارن"], jawapan: 2 },
  { soalan: "Ejaan Jawi bagi persatuan?", pilihan: ["ڤرساتوان", "ڤيرساتوان", "ڤرستوان", "ڤيرستوان"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi pertubuhan?", pilihan: ["ڤرتوبوهن", "ڤيرتوبوهن", "ڤرتبوهن", "ڤيرتبوهن"], jawapan: 0 },
  { soalan: "Ejaan Jawi bagi tanggungjawab?", pilihan: ["تاڠڬوڠجاوب", "تڠڬوڠجاوب", "تاڠڬوڠجوب", "تڠڬوڠجوب"], jawapan: 0 },
  { soalan: "Jawi ڤرجواڠن bermaksud?", pilihan: ["persatuan", "pertubuhan", "perjuangan", "pembangunan"], jawapan: 2 },
  { soalan: "Jawi کهارمونين bermaksud?", pilihan: ["keharmonian", "keberanian", "ketabahan", "kesabaran"], jawapan: 0 },
];

const PI_D5: QuizQuestion[] = [
  { soalan: "Apakah maksud aqidah?", pilihan: ["budi pekerti", "kepercayaan dan keyakinan dalam Islam", "ibadat", "akhlak"], jawapan: 1 },
  { soalan: "Apakah maksud syariah?", pilihan: ["aqidah", "akhlak", "undang-undang Islam", "budaya"], jawapan: 2 },
  { soalan: "Islam terdiri dari tiga bahagian iaitu?", pilihan: ["aqidah syariah akhlak", "solat puasa zakat", "iman islam ihsan", "rukun iman rukun islam sirah"], jawapan: 0 },
  { soalan: "Apakah maksud muamalat?", pilihan: ["ibadat khusus", "urusan sesama manusia", "akhlak", "aqidah"], jawapan: 1 },
  { soalan: "Apakah maksud ibadat?", pilihan: ["urusan manusia", "segala perbuatan kerana Allah", "akhlak sahaja", "solat sahaja"], jawapan: 1 },
  { soalan: "Nabi Muhammad SAW menerima wahyu pertama di?", pilihan: ["Masjidil Haram", "Madinah", "Gua Hira", "Padang Arafah"], jawapan: 2 },
  { soalan: "Tempoh Nabi berdakwah di Makkah?", pilihan: ["10 tahun", "13 tahun", "15 tahun", "23 tahun"], jawapan: 1 },
  { soalan: "Tempoh Nabi berdakwah di Madinah?", pilihan: ["5 tahun", "8 tahun", "10 tahun", "13 tahun"], jawapan: 2 },
  { soalan: "Perjanjian Hudaibiyyah berlaku pada tahun?", pilihan: ["4H", "5H", "6H", "7H"], jawapan: 2 },
  { soalan: "Pembukaan kota Makkah berlaku pada tahun?", pilihan: ["6H", "7H", "8H", "9H"], jawapan: 2 },
  { soalan: "Haji wida berlaku pada tahun?", pilihan: ["8H", "9H", "10H", "11H"], jawapan: 2 },
  { soalan: "Apakah maksud fardu ain?", pilihan: ["kewajipan kolektif", "kewajipan individu", "sunat", "harus"], jawapan: 1 },
  { soalan: "Apakah maksud fardu kifayah?", pilihan: ["kewajipan individu", "kewajipan kolektif", "sunat", "harus"], jawapan: 1 },
  { soalan: "Apakah maksud sunnah?", pilihan: ["wajib", "haram", "sesuatu yang dilakukan Nabi dan digalakkan", "makruh"], jawapan: 2 },
  { soalan: "Apakah maksud bidaah?", pilihan: ["sunnah", "perkara baru dalam agama yang tiada asas", "wajib", "harus"], jawapan: 1 },
];

const SAINS_D5: QuizQuestion[] = [
  { soalan: "Apakah DNA?", pilihan: ["protein", "bahan genetik dalam sel", "vitamin", "mineral"], jawapan: 1 },
  { soalan: "DNA terdapat dalam?", pilihan: ["sitoplasma", "dinding sel", "nukleus", "membran sel"], jawapan: 2 },
  { soalan: "Apakah kromosom?", pilihan: ["sel", "DNA yang tergulung", "protein", "vitamin"], jawapan: 1 },
  { soalan: "Apakah gen?", pilihan: ["unit pewarisan sifat", "sel", "tisu", "organ"], jawapan: 0 },
  { soalan: "Apakah pembiakan seks?", pilihan: ["satu induk", "dua induk jantan dan betina", "tanpa benih", "vegetatif"], jawapan: 1 },
  { soalan: "Apakah pembiakan aseks?", pilihan: ["dua induk", "satu induk tanpa penyatuan gamet", "memerlukan benih", "memerlukan bunga"], jawapan: 1 },
  { soalan: "Contoh pembiakan aseks pada tumbuhan?", pilihan: ["biji benih", "pendebungaan", "keratan batang", "buah"], jawapan: 2 },
  { soalan: "Apakah ekologi?", pilihan: ["kajian tentang sel", "kajian tentang hubungan organisma dengan persekitaran", "kajian tentang atom", "kajian tentang planet"], jawapan: 1 },
  { soalan: "Apakah biodiversiti?", pilihan: ["satu spesies", "kepelbagaian spesies hidupan", "satu ekosistem", "satu habitat"], jawapan: 1 },
  { soalan: "Ancaman kepada biodiversiti?", pilihan: ["menanam pokok", "pembalakan haram", "kitar semula", "taman negara"], jawapan: 1 },
  { soalan: "Cara pelihara biodiversiti?", pilihan: ["pembalakan", "pembangunan tanpa kawalan", "taman negara dan rizab alam", "pemburuan"], jawapan: 2 },
  { soalan: "Apakah tenaga nuklear?", pilihan: ["tenaga matahari", "tenaga angin", "tenaga dari pembelahan atom", "tenaga air"], jawapan: 2 },
  { soalan: "Apakah tenaga geoterma?", pilihan: ["tenaga matahari", "tenaga panas bumi", "tenaga angin", "tenaga air"], jawapan: 1 },
  { soalan: "Apakah kesan rumah hijau?", pilihan: ["sejukkan bumi", "panaskan bumi", "tiada kesan", "bersihkan udara"], jawapan: 1 },
  { soalan: "Gas rumah hijau contohnya?", pilihan: ["oksigen", "nitrogen", "karbon dioksida", "hidrogen"], jawapan: 2 },
];

// Key format: `${darjahId}:${subjekId}`
export const QUIZ_BANK: Record<string, QuizQuestion[]> = {
  "1:matematik": [
    { soalan: "Nombor apakah selepas 7?", pilihan: ["6", "8", "9", "10"], jawapan: 1, nota: "Selepas 7 ialah 8." },
    { soalan: "Nombor manakah paling besar?", pilihan: ["5", "12", "8", "15"], jawapan: 3, nota: "15 paling besar." },
    { soalan: "Nombor apakah sebelum 10?", pilihan: ["11", "10", "9", "8"], jawapan: 2, nota: "Sebelum 10 ialah 9." },
    { soalan: "3 + 4 = ?", pilihan: ["6", "7", "8", "9"], jawapan: 1 },
    { soalan: "10 - 3 = ?", pilihan: ["6", "8", "7", "13"], jawapan: 2 },
    { soalan: "5 + 5 = ?", pilihan: ["9", "10", "11", "55"], jawapan: 1 },
    { soalan: "8 - 4 = ?", pilihan: ["2", "3", "4", "12"], jawapan: 2 },
    { soalan: "Bentuk dengan 3 sisi ialah?", pilihan: ["Bulatan", "Segiempat", "Segitiga", "Segilima"], jawapan: 2 },
    { soalan: "Berapa sisi segiempat?", pilihan: ["2", "3", "4", "5"], jawapan: 2 },
    { soalan: "Siti ada 4 guli + Abu ada 5 guli = ?", pilihan: ["7", "8", "9", "10"], jawapan: 2 },
    { soalan: "10 oren - 3 dimakan = ?", pilihan: ["5", "6", "7", "8"], jawapan: 2 },
    { soalan: "1, 2, 3, ___, 5 — isi tempat kosong:", pilihan: ["2", "4", "6", "3"], jawapan: 1 },
    { soalan: "10, ___, 12, 13 — isi tempat kosong:", pilihan: ["9", "11", "10", "14"], jawapan: 1 },
    { soalan: "5 + 6 = ?", pilihan: ["9", "10", "11", "12"], jawapan: 2 },
    { soalan: "Ali ada 6 epal + 3 lagi = ?", pilihan: ["3", "8", "9", "10"], jawapan: 2 },
  ],
  "2:bahasa-melayu": [
    { soalan: "Pilih ayat yang betul:", pilihan: ["Ibu memasak nasi di dapur", "Ibu di dapur memasak nasi", "Memasak ibu nasi di dapur", "Di dapur ibu nasi memasak"], jawapan: 0 },
    { soalan: "Apakah imbuhan dalam perkataan 'berlari'?", pilihan: ["ber", "lari", "ri", "berl"], jawapan: 0 },
    { soalan: "Pilih kata nama:", pilihan: ["berlari", "cantik", "dengan", "meja"], jawapan: 3 },
    { soalan: "Apakah antonim 'rajin'?", pilihan: ["pandai", "malas", "sihat", "kuat"], jawapan: 1 },
    { soalan: "Pilih kata adjektif:", pilihan: ["berlari", "meja", "cantik", "dengan"], jawapan: 2 },
    { soalan: "Ayat manakah menggunakan tanda baca yang betul?", pilihan: ["ibu memasak nasi", "Ibu memasak nasi.", "ibu Memasak nasi", "Ibu memasak Nasi"], jawapan: 1 },
    { soalan: "Apakah sinonim 'gembira'?", pilihan: ["sedih", "marah", "suka", "takut"], jawapan: 2 },
    { soalan: "Pilih kata kerja:", pilihan: ["meja", "cantik", "berlari", "dengan"], jawapan: 2 },
    { soalan: "Ayat manakah ayat tanya?", pilihan: ["Ibu memasak nasi", "Tolong tutup pintu", "Di manakah buku saya", "Ambil buku itu"], jawapan: 2 },
    { soalan: "Apakah maksud peribahasa 'seperti aur dengan tebing'?", pilihan: ["Saling bergaduh", "Saling membantu", "Saling berdiam", "Saling bersaing"], jawapan: 1 },
    { soalan: "Pilih kata hubung:", pilihan: ["meja", "cantik", "berlari", "dan"], jawapan: 3 },
    { soalan: "Apakah imbuhan dalam 'pemimpin'?", pilihan: ["pe", "pem", "mimpin", "in"], jawapan: 1 },
    { soalan: "Pilih ayat perintah:", pilihan: ["Ibu memasak nasi", "Di mana buku saya", "Tolong tutup pintu", "Saya suka membaca"], jawapan: 2 },
    { soalan: "Apakah antonim 'besar'?", pilihan: ["tinggi", "panjang", "kecil", "lebar"], jawapan: 2 },
    { soalan: "Pilih kata sendi nama:", pilihan: ["berlari", "di", "cantik", "meja"], jawapan: 1 },
  ],
  "2:sains": SAINS_D2,
  "3:bahasa-melayu": BAHASA_MELAYU_D3,
  "3:matematik": MATE_D3,
  "3:bahasa-inggeris": BI_D3,
  "3:jawi": JAWI_D3,
  "3:pendidikan-islam": PI_D3,
  "3:sains": SAINS_D3,
  "4:bahasa-melayu": BM_D4,
  "4:matematik": MATE_D4,
  "4:bahasa-inggeris": BI_D4,
  "4:jawi": JAWI_D4,
  "4:pendidikan-islam": PI_D4,
  "4:sains": SAINS_D4,
};

export function getQuiz(darjahId: string, subjekId: string): QuizQuestion[] | undefined {
  return QUIZ_BANK[`${darjahId}:${subjekId}`];
}
