/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatihanRouteImport } from './routes/latihan'
import { Route as KuizRouteImport } from './routes/kuiz'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanRoute = LatihanRouteImport.update({
  id: '/latihan',
  path: '/latihan',
  getParentRoute: () => rootRouteImport,
} as any)
const KuizRoute = KuizRouteImport.update({
  id: '/kuiz',
  path: '/kuiz',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/kuiz': typeof KuizRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/kuiz': typeof KuizRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/kuiz': typeof KuizRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/daftar' | '/kuiz' | '/latihan' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daftar' | '/kuiz' | '/latihan' | '/login'
  id: '__root__' | '/' | '/daftar' | '/kuiz' | '/latihan' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarRoute: typeof DaftarRoute
  KuizRoute: typeof KuizRoute
  LatihanRoute: typeof LatihanRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan': {
      id: '/latihan'
      path: '/latihan'
      fullPath: '/latihan'
      preLoaderRoute: typeof LatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuiz': {
      id: '/kuiz'
      path: '/kuiz'
      fullPath: '/kuiz'
      preLoaderRoute: typeof KuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarRoute: DaftarRoute,
  KuizRoute: KuizRoute,
  LatihanRoute: LatihanRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
