/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LatihanRouteImport } from './routes/latihan'
import { Route as KuizRouteImport } from './routes/kuiz'
import { Route as IndexRouteImport } from './routes/index'

const LatihanRoute = LatihanRouteImport.update({
  id: '/latihan',
  path: '/latihan',
  getParentRoute: () => rootRouteImport,
} as any)
const KuizRoute = KuizRouteImport.update({
  id: '/kuiz',
  path: '/kuiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kuiz': typeof KuizRoute
  '/latihan': typeof LatihanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kuiz': typeof KuizRoute
  '/latihan': typeof LatihanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kuiz': typeof KuizRoute
  '/latihan': typeof LatihanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kuiz' | '/latihan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kuiz' | '/latihan'
  id: '__root__' | '/' | '/kuiz' | '/latihan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KuizRoute: typeof KuizRoute
  LatihanRoute: typeof LatihanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/latihan': {
      id: '/latihan'
      path: '/latihan'
      fullPath: '/latihan'
      preLoaderRoute: typeof LatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuiz': {
      id: '/kuiz'
      path: '/kuiz'
      fullPath: '/kuiz'
      preLoaderRoute: typeof KuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KuizRoute: KuizRoute,
  LatihanRoute: LatihanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
