/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UjianPercumaRouteImport } from './routes/ujian-percuma'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PilihDarjahRouteImport } from './routes/pilih-darjah'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LatihanRouteImport } from './routes/latihan'
import { Route as HargaRouteImport } from './routes/harga'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as CikguAffiliateRouteImport } from './routes/cikgu-affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewNamaRouteImport } from './routes/preview.nama'
import { Route as PreviewDarjahIdRouteImport } from './routes/preview.$darjahId'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as DashboardIbuBapaRouteImport } from './routes/dashboard.ibu-bapa'
import { Route as DarjahDarjahIdRouteImport } from './routes/darjah.$darjahId'
import { Route as BayaranSelesaiRouteImport } from './routes/bayaran.selesai'
import { Route as ApiTemporaryUnlockRouteImport } from './routes/api.temporary-unlock'
import { Route as ApiDebugEnvRouteImport } from './routes/api.debug-env'
import { Route as ApiConfirmPaymentRouteImport } from './routes/api.confirm-payment'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as AffiliateSyaratRouteImport } from './routes/affiliate.syarat'
import { Route as AffiliateDashboardRouteImport } from './routes/affiliate.dashboard'
import { Route as AffiliateDaftarRouteImport } from './routes/affiliate.daftar'
import { Route as AdminChallengeRouteImport } from './routes/admin_.challenge'
import { Route as AdminAffiliatesRouteImport } from './routes/admin_.affiliates'
import { Route as UjianPercumaSoalanSessionIdRouteImport } from './routes/ujian-percuma.soalan.$sessionId'
import { Route as PreviewDarjahIdScoreRouteImport } from './routes/preview.$darjahId_.score'
import { Route as DarjahDarjahIdSubjekIdRouteImport } from './routes/darjah.$darjahId_.$subjekId'
import { Route as DarjahDarjahIdSubjekIdNotaRingkasRouteImport } from './routes/darjah.$darjahId_.$subjekId_.nota-ringkas'
import { Route as DarjahDarjahIdSubjekIdLatihanRouteImport } from './routes/darjah.$darjahId_.$subjekId_.latihan'
import { Route as DarjahDarjahIdSubjekIdLatihTubiRouteImport } from './routes/darjah.$darjahId_.$subjekId_.latih-tubi'
import { Route as DarjahDarjahIdSubjekIdKuizRouteImport } from './routes/darjah.$darjahId_.$subjekId_.kuiz'
import { Route as DarjahDarjahIdSubjekIdIsiKosongRouteImport } from './routes/darjah.$darjahId_.$subjekId_.isi-kosong'
import { Route as DarjahDarjahIdSubjekIdGameRouteImport } from './routes/darjah.$darjahId_.$subjekId_.game'
import { Route as DarjahDarjahIdSubjekIdBergambarRajahRouteImport } from './routes/darjah.$darjahId_.$subjekId_.bergambar-rajah'
import { Route as ApiPublicToyyibpayCallbackRouteImport } from './routes/api.public.toyyibpay.callback'

const UjianPercumaRoute = UjianPercumaRouteImport.update({
  id: '/ujian-percuma',
  path: '/ujian-percuma',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PilihDarjahRoute = PilihDarjahRouteImport.update({
  id: '/pilih-darjah',
  path: '/pilih-darjah',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanRoute = LatihanRouteImport.update({
  id: '/latihan',
  path: '/latihan',
  getParentRoute: () => rootRouteImport,
} as any)
const HargaRoute = HargaRouteImport.update({
  id: '/harga',
  path: '/harga',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const CikguAffiliateRoute = CikguAffiliateRouteImport.update({
  id: '/cikgu-affiliate',
  path: '/cikgu-affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewNamaRoute = PreviewNamaRouteImport.update({
  id: '/preview/nama',
  path: '/preview/nama',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDarjahIdRoute = PreviewDarjahIdRouteImport.update({
  id: '/preview/$darjahId',
  path: '/preview/$darjahId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/dashboard/progress',
  path: '/dashboard/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIbuBapaRoute = DashboardIbuBapaRouteImport.update({
  id: '/dashboard/ibu-bapa',
  path: '/dashboard/ibu-bapa',
  getParentRoute: () => rootRouteImport,
} as any)
const DarjahDarjahIdRoute = DarjahDarjahIdRouteImport.update({
  id: '/darjah/$darjahId',
  path: '/darjah/$darjahId',
  getParentRoute: () => rootRouteImport,
} as any)
const BayaranSelesaiRoute = BayaranSelesaiRouteImport.update({
  id: '/bayaran/selesai',
  path: '/bayaran/selesai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemporaryUnlockRoute = ApiTemporaryUnlockRouteImport.update({
  id: '/api/temporary-unlock',
  path: '/api/temporary-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugEnvRoute = ApiDebugEnvRouteImport.update({
  id: '/api/debug-env',
  path: '/api/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmPaymentRoute = ApiConfirmPaymentRouteImport.update({
  id: '/api/confirm-payment',
  path: '/api/confirm-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateSyaratRoute = AffiliateSyaratRouteImport.update({
  id: '/affiliate/syarat',
  path: '/affiliate/syarat',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDashboardRoute = AffiliateDashboardRouteImport.update({
  id: '/affiliate/dashboard',
  path: '/affiliate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDaftarRoute = AffiliateDaftarRouteImport.update({
  id: '/affiliate/daftar',
  path: '/affiliate/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChallengeRoute = AdminChallengeRouteImport.update({
  id: '/admin_/challenge',
  path: '/admin/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/admin_/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianPercumaSoalanSessionIdRoute =
  UjianPercumaSoalanSessionIdRouteImport.update({
    id: '/soalan/$sessionId',
    path: '/soalan/$sessionId',
    getParentRoute: () => UjianPercumaRoute,
  } as any)
const PreviewDarjahIdScoreRoute = PreviewDarjahIdScoreRouteImport.update({
  id: '/preview/$darjahId_/score',
  path: '/preview/$darjahId/score',
  getParentRoute: () => rootRouteImport,
} as any)
const DarjahDarjahIdSubjekIdRoute = DarjahDarjahIdSubjekIdRouteImport.update({
  id: '/darjah/$darjahId_/$subjekId',
  path: '/darjah/$darjahId/$subjekId',
  getParentRoute: () => rootRouteImport,
} as any)
const DarjahDarjahIdSubjekIdNotaRingkasRoute =
  DarjahDarjahIdSubjekIdNotaRingkasRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/nota-ringkas',
    path: '/darjah/$darjahId/$subjekId/nota-ringkas',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarjahDarjahIdSubjekIdLatihanRoute =
  DarjahDarjahIdSubjekIdLatihanRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/latihan',
    path: '/darjah/$darjahId/$subjekId/latihan',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarjahDarjahIdSubjekIdLatihTubiRoute =
  DarjahDarjahIdSubjekIdLatihTubiRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/latih-tubi',
    path: '/darjah/$darjahId/$subjekId/latih-tubi',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarjahDarjahIdSubjekIdKuizRoute =
  DarjahDarjahIdSubjekIdKuizRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/kuiz',
    path: '/darjah/$darjahId/$subjekId/kuiz',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarjahDarjahIdSubjekIdIsiKosongRoute =
  DarjahDarjahIdSubjekIdIsiKosongRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/isi-kosong',
    path: '/darjah/$darjahId/$subjekId/isi-kosong',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarjahDarjahIdSubjekIdGameRoute =
  DarjahDarjahIdSubjekIdGameRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/game',
    path: '/darjah/$darjahId/$subjekId/game',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarjahDarjahIdSubjekIdBergambarRajahRoute =
  DarjahDarjahIdSubjekIdBergambarRajahRouteImport.update({
    id: '/darjah/$darjahId_/$subjekId_/bergambar-rajah',
    path: '/darjah/$darjahId/$subjekId/bergambar-rajah',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicToyyibpayCallbackRoute =
  ApiPublicToyyibpayCallbackRouteImport.update({
    id: '/api/public/toyyibpay/callback',
    path: '/api/public/toyyibpay/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cikgu-affiliate': typeof CikguAffiliateRoute
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/pilih-darjah': typeof PilihDarjahRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ujian-percuma': typeof UjianPercumaRouteWithChildren
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/affiliate/daftar': typeof AffiliateDaftarRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/syarat': typeof AffiliateSyaratRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/confirm-payment': typeof ApiConfirmPaymentRoute
  '/api/debug-env': typeof ApiDebugEnvRoute
  '/api/temporary-unlock': typeof ApiTemporaryUnlockRoute
  '/bayaran/selesai': typeof BayaranSelesaiRoute
  '/darjah/$darjahId': typeof DarjahDarjahIdRoute
  '/dashboard/ibu-bapa': typeof DashboardIbuBapaRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/preview/$darjahId': typeof PreviewDarjahIdRoute
  '/preview/nama': typeof PreviewNamaRoute
  '/darjah/$darjahId/$subjekId': typeof DarjahDarjahIdSubjekIdRoute
  '/preview/$darjahId/score': typeof PreviewDarjahIdScoreRoute
  '/ujian-percuma/soalan/$sessionId': typeof UjianPercumaSoalanSessionIdRoute
  '/api/public/toyyibpay/callback': typeof ApiPublicToyyibpayCallbackRoute
  '/darjah/$darjahId/$subjekId/bergambar-rajah': typeof DarjahDarjahIdSubjekIdBergambarRajahRoute
  '/darjah/$darjahId/$subjekId/game': typeof DarjahDarjahIdSubjekIdGameRoute
  '/darjah/$darjahId/$subjekId/isi-kosong': typeof DarjahDarjahIdSubjekIdIsiKosongRoute
  '/darjah/$darjahId/$subjekId/kuiz': typeof DarjahDarjahIdSubjekIdKuizRoute
  '/darjah/$darjahId/$subjekId/latih-tubi': typeof DarjahDarjahIdSubjekIdLatihTubiRoute
  '/darjah/$darjahId/$subjekId/latihan': typeof DarjahDarjahIdSubjekIdLatihanRoute
  '/darjah/$darjahId/$subjekId/nota-ringkas': typeof DarjahDarjahIdSubjekIdNotaRingkasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cikgu-affiliate': typeof CikguAffiliateRoute
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/pilih-darjah': typeof PilihDarjahRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ujian-percuma': typeof UjianPercumaRouteWithChildren
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/affiliate/daftar': typeof AffiliateDaftarRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/syarat': typeof AffiliateSyaratRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/confirm-payment': typeof ApiConfirmPaymentRoute
  '/api/debug-env': typeof ApiDebugEnvRoute
  '/api/temporary-unlock': typeof ApiTemporaryUnlockRoute
  '/bayaran/selesai': typeof BayaranSelesaiRoute
  '/darjah/$darjahId': typeof DarjahDarjahIdRoute
  '/dashboard/ibu-bapa': typeof DashboardIbuBapaRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/preview/$darjahId': typeof PreviewDarjahIdRoute
  '/preview/nama': typeof PreviewNamaRoute
  '/darjah/$darjahId/$subjekId': typeof DarjahDarjahIdSubjekIdRoute
  '/preview/$darjahId/score': typeof PreviewDarjahIdScoreRoute
  '/ujian-percuma/soalan/$sessionId': typeof UjianPercumaSoalanSessionIdRoute
  '/api/public/toyyibpay/callback': typeof ApiPublicToyyibpayCallbackRoute
  '/darjah/$darjahId/$subjekId/bergambar-rajah': typeof DarjahDarjahIdSubjekIdBergambarRajahRoute
  '/darjah/$darjahId/$subjekId/game': typeof DarjahDarjahIdSubjekIdGameRoute
  '/darjah/$darjahId/$subjekId/isi-kosong': typeof DarjahDarjahIdSubjekIdIsiKosongRoute
  '/darjah/$darjahId/$subjekId/kuiz': typeof DarjahDarjahIdSubjekIdKuizRoute
  '/darjah/$darjahId/$subjekId/latih-tubi': typeof DarjahDarjahIdSubjekIdLatihTubiRoute
  '/darjah/$darjahId/$subjekId/latihan': typeof DarjahDarjahIdSubjekIdLatihanRoute
  '/darjah/$darjahId/$subjekId/nota-ringkas': typeof DarjahDarjahIdSubjekIdNotaRingkasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cikgu-affiliate': typeof CikguAffiliateRoute
  '/daftar': typeof DaftarRoute
  '/harga': typeof HargaRoute
  '/latihan': typeof LatihanRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/pilih-darjah': typeof PilihDarjahRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ujian-percuma': typeof UjianPercumaRouteWithChildren
  '/admin_/affiliates': typeof AdminAffiliatesRoute
  '/admin_/challenge': typeof AdminChallengeRoute
  '/affiliate/daftar': typeof AffiliateDaftarRoute
  '/affiliate/dashboard': typeof AffiliateDashboardRoute
  '/affiliate/syarat': typeof AffiliateSyaratRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/confirm-payment': typeof ApiConfirmPaymentRoute
  '/api/debug-env': typeof ApiDebugEnvRoute
  '/api/temporary-unlock': typeof ApiTemporaryUnlockRoute
  '/bayaran/selesai': typeof BayaranSelesaiRoute
  '/darjah/$darjahId': typeof DarjahDarjahIdRoute
  '/dashboard/ibu-bapa': typeof DashboardIbuBapaRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/preview/$darjahId': typeof PreviewDarjahIdRoute
  '/preview/nama': typeof PreviewNamaRoute
  '/darjah/$darjahId_/$subjekId': typeof DarjahDarjahIdSubjekIdRoute
  '/preview/$darjahId_/score': typeof PreviewDarjahIdScoreRoute
  '/ujian-percuma/soalan/$sessionId': typeof UjianPercumaSoalanSessionIdRoute
  '/api/public/toyyibpay/callback': typeof ApiPublicToyyibpayCallbackRoute
  '/darjah/$darjahId_/$subjekId_/bergambar-rajah': typeof DarjahDarjahIdSubjekIdBergambarRajahRoute
  '/darjah/$darjahId_/$subjekId_/game': typeof DarjahDarjahIdSubjekIdGameRoute
  '/darjah/$darjahId_/$subjekId_/isi-kosong': typeof DarjahDarjahIdSubjekIdIsiKosongRoute
  '/darjah/$darjahId_/$subjekId_/kuiz': typeof DarjahDarjahIdSubjekIdKuizRoute
  '/darjah/$darjahId_/$subjekId_/latih-tubi': typeof DarjahDarjahIdSubjekIdLatihTubiRoute
  '/darjah/$darjahId_/$subjekId_/latihan': typeof DarjahDarjahIdSubjekIdLatihanRoute
  '/darjah/$darjahId_/$subjekId_/nota-ringkas': typeof DarjahDarjahIdSubjekIdNotaRingkasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cikgu-affiliate'
    | '/daftar'
    | '/harga'
    | '/latihan'
    | '/login'
    | '/lupa-password'
    | '/pilih-darjah'
    | '/reset-password'
    | '/ujian-percuma'
    | '/admin/affiliates'
    | '/admin/challenge'
    | '/affiliate/daftar'
    | '/affiliate/dashboard'
    | '/affiliate/syarat'
    | '/api/checkout'
    | '/api/confirm-payment'
    | '/api/debug-env'
    | '/api/temporary-unlock'
    | '/bayaran/selesai'
    | '/darjah/$darjahId'
    | '/dashboard/ibu-bapa'
    | '/dashboard/progress'
    | '/preview/$darjahId'
    | '/preview/nama'
    | '/darjah/$darjahId/$subjekId'
    | '/preview/$darjahId/score'
    | '/ujian-percuma/soalan/$sessionId'
    | '/api/public/toyyibpay/callback'
    | '/darjah/$darjahId/$subjekId/bergambar-rajah'
    | '/darjah/$darjahId/$subjekId/game'
    | '/darjah/$darjahId/$subjekId/isi-kosong'
    | '/darjah/$darjahId/$subjekId/kuiz'
    | '/darjah/$darjahId/$subjekId/latih-tubi'
    | '/darjah/$darjahId/$subjekId/latihan'
    | '/darjah/$darjahId/$subjekId/nota-ringkas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cikgu-affiliate'
    | '/daftar'
    | '/harga'
    | '/latihan'
    | '/login'
    | '/lupa-password'
    | '/pilih-darjah'
    | '/reset-password'
    | '/ujian-percuma'
    | '/admin/affiliates'
    | '/admin/challenge'
    | '/affiliate/daftar'
    | '/affiliate/dashboard'
    | '/affiliate/syarat'
    | '/api/checkout'
    | '/api/confirm-payment'
    | '/api/debug-env'
    | '/api/temporary-unlock'
    | '/bayaran/selesai'
    | '/darjah/$darjahId'
    | '/dashboard/ibu-bapa'
    | '/dashboard/progress'
    | '/preview/$darjahId'
    | '/preview/nama'
    | '/darjah/$darjahId/$subjekId'
    | '/preview/$darjahId/score'
    | '/ujian-percuma/soalan/$sessionId'
    | '/api/public/toyyibpay/callback'
    | '/darjah/$darjahId/$subjekId/bergambar-rajah'
    | '/darjah/$darjahId/$subjekId/game'
    | '/darjah/$darjahId/$subjekId/isi-kosong'
    | '/darjah/$darjahId/$subjekId/kuiz'
    | '/darjah/$darjahId/$subjekId/latih-tubi'
    | '/darjah/$darjahId/$subjekId/latihan'
    | '/darjah/$darjahId/$subjekId/nota-ringkas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cikgu-affiliate'
    | '/daftar'
    | '/harga'
    | '/latihan'
    | '/login'
    | '/lupa-password'
    | '/pilih-darjah'
    | '/reset-password'
    | '/ujian-percuma'
    | '/admin_/affiliates'
    | '/admin_/challenge'
    | '/affiliate/daftar'
    | '/affiliate/dashboard'
    | '/affiliate/syarat'
    | '/api/checkout'
    | '/api/confirm-payment'
    | '/api/debug-env'
    | '/api/temporary-unlock'
    | '/bayaran/selesai'
    | '/darjah/$darjahId'
    | '/dashboard/ibu-bapa'
    | '/dashboard/progress'
    | '/preview/$darjahId'
    | '/preview/nama'
    | '/darjah/$darjahId_/$subjekId'
    | '/preview/$darjahId_/score'
    | '/ujian-percuma/soalan/$sessionId'
    | '/api/public/toyyibpay/callback'
    | '/darjah/$darjahId_/$subjekId_/bergambar-rajah'
    | '/darjah/$darjahId_/$subjekId_/game'
    | '/darjah/$darjahId_/$subjekId_/isi-kosong'
    | '/darjah/$darjahId_/$subjekId_/kuiz'
    | '/darjah/$darjahId_/$subjekId_/latih-tubi'
    | '/darjah/$darjahId_/$subjekId_/latihan'
    | '/darjah/$darjahId_/$subjekId_/nota-ringkas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CikguAffiliateRoute: typeof CikguAffiliateRoute
  DaftarRoute: typeof DaftarRoute
  HargaRoute: typeof HargaRoute
  LatihanRoute: typeof LatihanRoute
  LoginRoute: typeof LoginRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  PilihDarjahRoute: typeof PilihDarjahRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UjianPercumaRoute: typeof UjianPercumaRouteWithChildren
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminChallengeRoute: typeof AdminChallengeRoute
  AffiliateDaftarRoute: typeof AffiliateDaftarRoute
  AffiliateDashboardRoute: typeof AffiliateDashboardRoute
  AffiliateSyaratRoute: typeof AffiliateSyaratRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiConfirmPaymentRoute: typeof ApiConfirmPaymentRoute
  ApiDebugEnvRoute: typeof ApiDebugEnvRoute
  ApiTemporaryUnlockRoute: typeof ApiTemporaryUnlockRoute
  BayaranSelesaiRoute: typeof BayaranSelesaiRoute
  DarjahDarjahIdRoute: typeof DarjahDarjahIdRoute
  DashboardIbuBapaRoute: typeof DashboardIbuBapaRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  PreviewDarjahIdRoute: typeof PreviewDarjahIdRoute
  PreviewNamaRoute: typeof PreviewNamaRoute
  DarjahDarjahIdSubjekIdRoute: typeof DarjahDarjahIdSubjekIdRoute
  PreviewDarjahIdScoreRoute: typeof PreviewDarjahIdScoreRoute
  ApiPublicToyyibpayCallbackRoute: typeof ApiPublicToyyibpayCallbackRoute
  DarjahDarjahIdSubjekIdBergambarRajahRoute: typeof DarjahDarjahIdSubjekIdBergambarRajahRoute
  DarjahDarjahIdSubjekIdGameRoute: typeof DarjahDarjahIdSubjekIdGameRoute
  DarjahDarjahIdSubjekIdIsiKosongRoute: typeof DarjahDarjahIdSubjekIdIsiKosongRoute
  DarjahDarjahIdSubjekIdKuizRoute: typeof DarjahDarjahIdSubjekIdKuizRoute
  DarjahDarjahIdSubjekIdLatihTubiRoute: typeof DarjahDarjahIdSubjekIdLatihTubiRoute
  DarjahDarjahIdSubjekIdLatihanRoute: typeof DarjahDarjahIdSubjekIdLatihanRoute
  DarjahDarjahIdSubjekIdNotaRingkasRoute: typeof DarjahDarjahIdSubjekIdNotaRingkasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ujian-percuma': {
      id: '/ujian-percuma'
      path: '/ujian-percuma'
      fullPath: '/ujian-percuma'
      preLoaderRoute: typeof UjianPercumaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilih-darjah': {
      id: '/pilih-darjah'
      path: '/pilih-darjah'
      fullPath: '/pilih-darjah'
      preLoaderRoute: typeof PilihDarjahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan': {
      id: '/latihan'
      path: '/latihan'
      fullPath: '/latihan'
      preLoaderRoute: typeof LatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harga': {
      id: '/harga'
      path: '/harga'
      fullPath: '/harga'
      preLoaderRoute: typeof HargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cikgu-affiliate': {
      id: '/cikgu-affiliate'
      path: '/cikgu-affiliate'
      fullPath: '/cikgu-affiliate'
      preLoaderRoute: typeof CikguAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/nama': {
      id: '/preview/nama'
      path: '/preview/nama'
      fullPath: '/preview/nama'
      preLoaderRoute: typeof PreviewNamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$darjahId': {
      id: '/preview/$darjahId'
      path: '/preview/$darjahId'
      fullPath: '/preview/$darjahId'
      preLoaderRoute: typeof PreviewDarjahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/dashboard/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ibu-bapa': {
      id: '/dashboard/ibu-bapa'
      path: '/dashboard/ibu-bapa'
      fullPath: '/dashboard/ibu-bapa'
      preLoaderRoute: typeof DashboardIbuBapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId': {
      id: '/darjah/$darjahId'
      path: '/darjah/$darjahId'
      fullPath: '/darjah/$darjahId'
      preLoaderRoute: typeof DarjahDarjahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bayaran/selesai': {
      id: '/bayaran/selesai'
      path: '/bayaran/selesai'
      fullPath: '/bayaran/selesai'
      preLoaderRoute: typeof BayaranSelesaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/temporary-unlock': {
      id: '/api/temporary-unlock'
      path: '/api/temporary-unlock'
      fullPath: '/api/temporary-unlock'
      preLoaderRoute: typeof ApiTemporaryUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-env': {
      id: '/api/debug-env'
      path: '/api/debug-env'
      fullPath: '/api/debug-env'
      preLoaderRoute: typeof ApiDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm-payment': {
      id: '/api/confirm-payment'
      path: '/api/confirm-payment'
      fullPath: '/api/confirm-payment'
      preLoaderRoute: typeof ApiConfirmPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/syarat': {
      id: '/affiliate/syarat'
      path: '/affiliate/syarat'
      fullPath: '/affiliate/syarat'
      preLoaderRoute: typeof AffiliateSyaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/dashboard': {
      id: '/affiliate/dashboard'
      path: '/affiliate/dashboard'
      fullPath: '/affiliate/dashboard'
      preLoaderRoute: typeof AffiliateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/daftar': {
      id: '/affiliate/daftar'
      path: '/affiliate/daftar'
      fullPath: '/affiliate/daftar'
      preLoaderRoute: typeof AffiliateDaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/challenge': {
      id: '/admin_/challenge'
      path: '/admin/challenge'
      fullPath: '/admin/challenge'
      preLoaderRoute: typeof AdminChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/affiliates': {
      id: '/admin_/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian-percuma/soalan/$sessionId': {
      id: '/ujian-percuma/soalan/$sessionId'
      path: '/soalan/$sessionId'
      fullPath: '/ujian-percuma/soalan/$sessionId'
      preLoaderRoute: typeof UjianPercumaSoalanSessionIdRouteImport
      parentRoute: typeof UjianPercumaRoute
    }
    '/preview/$darjahId_/score': {
      id: '/preview/$darjahId_/score'
      path: '/preview/$darjahId/score'
      fullPath: '/preview/$darjahId/score'
      preLoaderRoute: typeof PreviewDarjahIdScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId': {
      id: '/darjah/$darjahId_/$subjekId'
      path: '/darjah/$darjahId/$subjekId'
      fullPath: '/darjah/$darjahId/$subjekId'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/nota-ringkas': {
      id: '/darjah/$darjahId_/$subjekId_/nota-ringkas'
      path: '/darjah/$darjahId/$subjekId/nota-ringkas'
      fullPath: '/darjah/$darjahId/$subjekId/nota-ringkas'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdNotaRingkasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/latihan': {
      id: '/darjah/$darjahId_/$subjekId_/latihan'
      path: '/darjah/$darjahId/$subjekId/latihan'
      fullPath: '/darjah/$darjahId/$subjekId/latihan'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdLatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/latih-tubi': {
      id: '/darjah/$darjahId_/$subjekId_/latih-tubi'
      path: '/darjah/$darjahId/$subjekId/latih-tubi'
      fullPath: '/darjah/$darjahId/$subjekId/latih-tubi'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdLatihTubiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/kuiz': {
      id: '/darjah/$darjahId_/$subjekId_/kuiz'
      path: '/darjah/$darjahId/$subjekId/kuiz'
      fullPath: '/darjah/$darjahId/$subjekId/kuiz'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdKuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/isi-kosong': {
      id: '/darjah/$darjahId_/$subjekId_/isi-kosong'
      path: '/darjah/$darjahId/$subjekId/isi-kosong'
      fullPath: '/darjah/$darjahId/$subjekId/isi-kosong'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdIsiKosongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/game': {
      id: '/darjah/$darjahId_/$subjekId_/game'
      path: '/darjah/$darjahId/$subjekId/game'
      fullPath: '/darjah/$darjahId/$subjekId/game'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darjah/$darjahId_/$subjekId_/bergambar-rajah': {
      id: '/darjah/$darjahId_/$subjekId_/bergambar-rajah'
      path: '/darjah/$darjahId/$subjekId/bergambar-rajah'
      fullPath: '/darjah/$darjahId/$subjekId/bergambar-rajah'
      preLoaderRoute: typeof DarjahDarjahIdSubjekIdBergambarRajahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/toyyibpay/callback': {
      id: '/api/public/toyyibpay/callback'
      path: '/api/public/toyyibpay/callback'
      fullPath: '/api/public/toyyibpay/callback'
      preLoaderRoute: typeof ApiPublicToyyibpayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UjianPercumaRouteChildren {
  UjianPercumaSoalanSessionIdRoute: typeof UjianPercumaSoalanSessionIdRoute
}

const UjianPercumaRouteChildren: UjianPercumaRouteChildren = {
  UjianPercumaSoalanSessionIdRoute: UjianPercumaSoalanSessionIdRoute,
}

const UjianPercumaRouteWithChildren = UjianPercumaRoute._addFileChildren(
  UjianPercumaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CikguAffiliateRoute: CikguAffiliateRoute,
  DaftarRoute: DaftarRoute,
  HargaRoute: HargaRoute,
  LatihanRoute: LatihanRoute,
  LoginRoute: LoginRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  PilihDarjahRoute: PilihDarjahRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UjianPercumaRoute: UjianPercumaRouteWithChildren,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminChallengeRoute: AdminChallengeRoute,
  AffiliateDaftarRoute: AffiliateDaftarRoute,
  AffiliateDashboardRoute: AffiliateDashboardRoute,
  AffiliateSyaratRoute: AffiliateSyaratRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiConfirmPaymentRoute: ApiConfirmPaymentRoute,
  ApiDebugEnvRoute: ApiDebugEnvRoute,
  ApiTemporaryUnlockRoute: ApiTemporaryUnlockRoute,
  BayaranSelesaiRoute: BayaranSelesaiRoute,
  DarjahDarjahIdRoute: DarjahDarjahIdRoute,
  DashboardIbuBapaRoute: DashboardIbuBapaRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  PreviewDarjahIdRoute: PreviewDarjahIdRoute,
  PreviewNamaRoute: PreviewNamaRoute,
  DarjahDarjahIdSubjekIdRoute: DarjahDarjahIdSubjekIdRoute,
  PreviewDarjahIdScoreRoute: PreviewDarjahIdScoreRoute,
  ApiPublicToyyibpayCallbackRoute: ApiPublicToyyibpayCallbackRoute,
  DarjahDarjahIdSubjekIdBergambarRajahRoute:
    DarjahDarjahIdSubjekIdBergambarRajahRoute,
  DarjahDarjahIdSubjekIdGameRoute: DarjahDarjahIdSubjekIdGameRoute,
  DarjahDarjahIdSubjekIdIsiKosongRoute: DarjahDarjahIdSubjekIdIsiKosongRoute,
  DarjahDarjahIdSubjekIdKuizRoute: DarjahDarjahIdSubjekIdKuizRoute,
  DarjahDarjahIdSubjekIdLatihTubiRoute: DarjahDarjahIdSubjekIdLatihTubiRoute,
  DarjahDarjahIdSubjekIdLatihanRoute: DarjahDarjahIdSubjekIdLatihanRoute,
  DarjahDarjahIdSubjekIdNotaRingkasRoute:
    DarjahDarjahIdSubjekIdNotaRingkasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
